# Cloud Build configuration for automated CI/CD
steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    
  # Build and test (add tests if you have them)
  # - name: 'node:20'
  #   entrypoint: npm
  #   args: ['test']
    
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/franchise-service:$COMMIT_SHA', '.']
    
  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/franchise-service:$COMMIT_SHA']
    
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'franchise-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/franchise-service:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/franchise-service:$COMMIT_SHA'